// Maintains the live preview index. Zero dependencies, Node built-ins only.
//
//   node preview-index.mjs upsert <manifest> <branch> <url> <sha> <updated>
//   node preview-index.mjs remove <manifest> <branch>
//   node preview-index.mjs sync-prs <manifest>
//   node preview-index.mjs render <manifest> <readme>
//
// The manifest is a JSON array of { branch, url, sha, updated, pr? }, where pr
// is { number, url } for the open pull request whose head is that branch.
// sync-prs reads GITHUB_REPOSITORY and GITHUB_TOKEN from the environment, asks
// the GitHub API for the open pull requests, and refreshes the pr field on each
// entry (setting it when a PR is open for the branch, dropping it otherwise).
// render writes a table between the PREVIEWS markers in the README, appending
// it at the end if the markers are not present. render never touches the
// network, so it stays deterministic.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const START = '<!-- PREVIEWS:START -->';
const END = '<!-- PREVIEWS:END -->';

const load = (p) => (existsSync(p) ? JSON.parse(readFileSync(p, 'utf8') || '[]') : []);
const save = (p, d) => writeFileSync(p, JSON.stringify(d, null, 2) + '\n');

// master first, then alphabetical.
const order = (a, b) =>
  a.branch === b.branch ? 0
    : a.branch === 'master' ? -1
    : b.branch === 'master' ? 1
    : a.branch.localeCompare(b.branch);

// Map of head branch name to { number, url } for every open pull request.
// Returns an empty map when the repo or token is missing, so the command
// degrades to "no PRs known" rather than failing.
async function fetchOpenPrs() {
  const repo = process.env.GITHUB_REPOSITORY;
  const token = process.env.GITHUB_TOKEN;
  const map = new Map();
  if (!repo || !token) return map;

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'inkfall-preview-index',
  };

  for (let page = 1; ; page++) {
    const res = await fetch(
      `https://api.github.com/repos/${repo}/pulls?state=open&per_page=100&page=${page}`,
      { headers },
    );
    if (!res.ok) {
      throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
    }
    const prs = await res.json();
    for (const pr of prs) {
      // Lowest numbered open PR wins when a branch somehow has more than one.
      if (!map.has(pr.head.ref)) {
        map.set(pr.head.ref, { number: pr.number, url: pr.html_url });
      }
    }
    if (prs.length < 100) break;
  }
  return map;
}

const [cmd, ...rest] = process.argv.slice(2);

if (cmd === 'upsert') {
  const [manifest, branch, url, sha, updated] = rest;
  const list = load(manifest);
  // Idempotency: keep the existing timestamp when the commit has not changed,
  // so re-running with the same state produces an identical manifest and no
  // diff. This makes the index self terminating, a loop cannot sustain itself.
  const prev = list.find((e) => e.branch === branch);
  const stamp = prev && prev.sha === sha ? prev.updated : updated;
  const next = list.filter((e) => e.branch !== branch);
  const entry = { branch, url, sha, updated: stamp };
  // Carry the open PR link across pushes. sync-prs refreshes it afterwards.
  if (prev && prev.pr) entry.pr = prev.pr;
  next.push(entry);
  next.sort(order);
  save(manifest, next);
} else if (cmd === 'remove') {
  const [manifest, branch] = rest;
  save(manifest, load(manifest).filter((e) => e.branch !== branch));
} else if (cmd === 'sync-prs') {
  const [manifest] = rest;
  const list = load(manifest);
  const open = await fetchOpenPrs();
  for (const e of list) {
    const pr = open.get(e.branch);
    if (pr) e.pr = pr;
    else delete e.pr;
  }
  list.sort(order);
  save(manifest, list);
} else if (cmd === 'render') {
  const [manifest, readme] = rest;
  const list = load(manifest).sort(order);

  const block = [
    START,
    '## Live previews',
    '',
    'Auto generated by the Branch previews workflow. Do not edit by hand.',
    '',
    ...(list.length
      ? [
          '| Branch | Preview | PR | Updated (UTC) | Commit |',
          '| --- | --- | --- | --- | --- |',
          ...list.map(
            (e) =>
              `| \`${e.branch}\` | [open](${e.url}) | ${
                e.pr ? `[#${e.pr.number}](${e.pr.url})` : '-'
              } | ${e.updated} | \`${e.sha}\` |`,
          ),
        ]
      : ['_No previews are currently deployed._']),
    END,
  ].join('\n');

  let md = readFileSync(readme, 'utf8');
  if (md.includes(START) && md.includes(END)) {
    md = md.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block);
  } else {
    md = md.replace(/\s*$/, '') + '\n\n' + block + '\n';
  }
  writeFileSync(readme, md);
} else {
  console.error(`unknown command: ${cmd}`);
  process.exit(1);
}
